export enum Skills {
  js = 'JavaScript/Front-End',
  java = 'Java',
  c_sharp = 'C#',
  net = '.NET',
  python = 'Python',
  php = 'PHP',
  node = 'Node.js',
  ios = 'IOS',
  android = 'Android',
  c = 'C',
  c_plus = 'C++',
  embedded = 'Embedded',
  flutter = 'Flutter',
  golang = 'Golang',
  ruby = 'Ruby',
  scala = 'Scala',
  salesforce = 'Salesforce',
  rust = 'Rust',
  other = 'Other',
}
